- name: Install docker.io
  apt:
    name: docker.io
    update_cache: yes

- name: Create docker directory
  file:
    path: "/home/{{ user.name }}/docker"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
