- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: 0770

- name: Copy docker-compose.yml
  copy:
    src: ./docker-compose.yml
    dest: "/home/{{ user.name }}/docker/docker-compose.yml"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550