FROM php:7.3-fpm

USER root

RUN apt-get update
RUN apt-get -y install openssl \
                       git \
                       zip \
                       supervisor

# --- Install composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

# --- Setup user
RUN groupadd --gid {{ group.gid }} {{ group.name }}
RUN useradd {{ user.name }} --uid {{ user.uid }} -m -g {{ group.name }}
RUN echo "{{ user.name }}:{{ user.password }}" | chpasswd

# --- Configure supervisord
COPY ./etc/supervisor/conf.d/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# --- Install xdebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

RUN sed -i 's/www-data/{{ user.name }}/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/www-data/{{ user.name }}/g' /usr/local/etc/php-fpm.d/www.conf.default
RUN sed -i 's/listen = 127.0.0.1:9000/listen = 0.0.0.0:9000/g' /usr/local/etc/php-fpm.d/www.conf

COPY ./usr/local/etc/php/php.ini /usr/local/etc/php/php.ini
RUN chmod 0775 /usr/local/etc/php/php.ini

WORKDIR /var/www/html/code

EXPOSE 9000 9001

CMD [ "supervisord", "-n" ]