- name: Create docker_nginx directory
  file:
    path: "/home/{{ user.name }}/docker/nginx"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy Dockerfile
  template:
    src: ./Dockerfile.j2
    dest: "/home/{{ user.name }}/docker/nginx/Dockerfile"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create etc directories
  file:
    path: "/home/{{ user.name }}/docker/nginx/etc/nginx/"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy nginx.conf
  template:
    src: ./etc/nginx/nginx.conf.j2
    dest: "/home/{{ user.name }}/docker/nginx/etc/nginx/nginx.conf"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create sites-enabled directories
  file:
    path: "/home/{{ user.name }}/docker/nginx/etc/nginx/sites-enabled"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy sites configs
  copy:
    src: "./etc/nginx/sites-enabled/{{ item }}.conf"
    dest: "/home/{{ user.name }}/docker/nginx/etc/nginx/sites-enabled/{{ item }}.conf"
    group: docker
    mode: 0550
  with_items:
    - "lab.local"
    - "attacker.local"

- name: Create ssl directories
  file:
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory
  with_items:
    - "/home/{{ user.name }}/docker/nginx/etc/ssl/private"
    - "/home/{{ user.name }}/docker/nginx/etc/ssl/certs"

- name: Generate OpenSSL private keys
  openssl_privatekey:
    path: "/home/{{ user.name }}/docker/nginx/etc/ssl/private/{{ item }}.key"
  with_items:
    - "lab.local"
    - "attacker.local"

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "/home/{{ user.name }}/docker/nginx/etc/ssl/private/{{ item }}.csr"
    privatekey_path: "/home/{{ user.name }}/docker/nginx/etc/ssl/private/{{ item }}.key"
    common_name: "{{ item }}"
  with_items:
    - "lab.local"
    - "attacker.local"

- name: Create openssl certificate
  openssl_certificate:
    path: "/home/{{ user.name }}/docker/nginx/etc/ssl/certs/{{ item }}.crt"
    privatekey_path: "/home/{{ user.name }}/docker/nginx/etc/ssl/private/{{ item }}.key"
    csr_path: "/home/{{ user.name }}/docker/nginx/etc/ssl/private/{{ item }}.csr"
    provider: selfsigned
  with_items:
    - "lab.local"
    - "attacker.local"

- name: Change ssl directory permissions
  file:
    path: "/home/{{ user.name }}/docker/nginx/etc/ssl"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory
    recurse: yes