version: "2.4"

networks:
  default:
    ipam:
      config:
        - subnet: 170.20.0.0/24
services:
  nginx:
    build: "./nginx/"
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/log/nginx/:/var/log/nginx/
    - /var/www/html/code/:/var/www/html/code/
    networks:
      default:
        ipv4_address: 170.20.0.2
  php:
    build: "./php/"
    volumes:
      - /var/www/html/code/:/var/www/html/code/
    networks:
      default:
        ipv4_address: 170.20.0.3