- name: Create docker_php directory
  file:
    path: "/home/{{ user.name }}/docker/php1"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy Dockerfile
  template:
    src: ./Dockerfile.j2
    dest: "/home/{{ user.name }}/docker/php1/Dockerfile"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create supervisord directory
  file:
    path: "/home/{{ user.name }}/docker/php1/etc/supervisor/conf.d/"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy supervisord.conf
  copy:
    src: ./etc/supervisor/conf.d/supervisord.conf
    dest: "/home/{{ user.name }}/docker/php1/etc/supervisor/conf.d/supervisord.conf"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create php directory
  file:
    path: "/home/{{ user.name }}/docker/php1/usr/local/etc/php/"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy php.ini
  copy:
    src: ./usr/local/etc/php/php.ini
    dest: "/home/{{ user.name }}/docker/php1/usr/local/etc/php/php.ini"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550